version: '3'
services:
  postgres:
    container_name: postgres-intensive-project
    build:
      context: ./
      dockerfile: Dockerfile_db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./scriptSQL:/docker-entrypoint-initdb.d